# Generated by Django 5.1.6 on 2025-03-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_alter_parkinglog_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
